name: Unit tests
on:
  pull_request:
  push:
    branches: [master]
jobs:
  unit:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        go mod download
    - name: Run Unit tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -v -coverpkg=./.. ./...
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
